name: $(Date:yyyyMMdd)$(Rev:.r)
trigger:
  branches:
    include:
      - refs/heads/dev
      - refs/heads/qa
      - refs/heads/uat
      - refs/heads/main
  paths:
    exclude:
    - README.md

pr:
  branches:
    include:
      - refs/heads/dev
      - refs/heads/qa
      - refs/heads/uat
      - refs/heads/main
  paths:
    exclude:
    - README.md
    
pool:
  name: Default # CHANGE HERE AFTER FORK REPO
  vmImage: hosted-azure # CHANGE HERE AFTER FORK REPO

resources:
  repositories:
    - repository: devopsRepo # CHANGE HERE AFTER FORK REPO
      type: github
      endpoint: github.com_alexbaptista # CHANGE HERE AFTER FORK REPO
      name: alexbaptista/azuredevops-iac-template-pipeline # CHANGE HERE AFTER FORK REPO

extends:
  template: template.yaml
  parameters:
    envConfig:
      DEV:
        gitBranch: refs/heads/dev
        variablesGroup: azuredevops-iac-template-pipeline
      QA:
        gitBranch: refs/heads/qa
        variablesGroup: azuredevops-iac-template-pipeline
      UAT:
        gitBranch: refs/heads/uat
        variablesGroup: azuredevops-iac-template-pipeline
      PRD:
        gitBranch: refs/heads/main
        variablesGroup: azuredevops-iac-template-pipeline
      Terraform:
        terraformVersion: 1.2.9
        terraformPath: $(System.DefaultWorkingDirectory)/example-iac
