name: $(Date:yyyyMMdd)$(Rev:.r)
trigger:
  branches:
    include:
      - refs/heads/dev
      - refs/heads/qa
      - refs/heads/uat
      - refs/heads/main
  paths:
    exclude:
    - README.md

pr:
  branches:
    include:
      - refs/heads/dev
      - refs/heads/qa
      - refs/heads/uat
      - refs/heads/main
  paths:
    exclude:
    - README.md
    
pool:
  name: Default # CHANGE HERE AFTER FORK REPO
  vmImage: hosted-azure # CHANGE HERE AFTER FORK REPO

resources:
  repositories:
    - repository: devopsRepo # CHANGE HERE AFTER FORK REPO
      type: github
      endpoint: github.com_alexbaptista # CHANGE HERE AFTER FORK REPO
      name: alexbaptista/azuredevops-iac-template-pipeline # CHANGE HERE AFTER FORK REPO
  containers:
    - container: terraform
      image: docker.io/alxbap/azuredevops-iac-template-pipeline:v.1.2

stages:
  - template: pipeline/terraform.yaml
    parameters:
      terraformPath: $(System.DefaultWorkingDirectory)/example-iac
      terraformVersion: 1.2.7
      resourceContainer: terraform
      variableGroup: azuredevops-iac-template-pipeline
      envConfig:
        DEV:
          environmentDeploy: dev
          gitBranch: refs/heads/dev
        QA:
          environmentDeploy: qa
          gitBranch: refs/heads/qa
        UAT:
          environmentDeploy: uat
          gitBranch: refs/heads/uat
        PRD:
          environmentDeploy: prd
          gitBranch: refs/heads/main