extends:
  template: template.yaml
  parameters:
    envConfig:
      DEV:
        gitBranch: refs/heads/dev
        variablesGroup: azuredevops-iac-template-pipeline
      QA:
        gitBranch: refs/heads/qa
        variablesGroup: azuredevops-iac-template-pipeline
      UAT:
        gitBranch: refs/heads/uat
        variablesGroup: azuredevops-iac-template-pipeline
      PRD:
        gitBranch: refs/heads/main
        variablesGroup: azuredevops-iac-template-pipeline
      Terraform:
        terraformVersion: 1.2.9
        terraformPath: $(System.DefaultWorkingDirectory)/example-iac
