name: $(Date:yyyyMMdd)$(Rev:.r)
trigger:
  branches:
    include:
      - dev
      - qa
      - uat
      - main

pr:
  branches:
    include:
      - dev
      - qa
      - uat
      - main

variables:
  - group: azuredevops-iac-template-pipeline

pool:
  name: Default
  vmImage: hosted-azure

resources:
  repositories:
    - repository: devopsRepo
      type: github
      endpoint: github.com_alexbaptista # CHANGE HERE AFTER FORK REPO
      name: alexbaptista/azuredevops-iac-template-pipeline # CHANGE HERE AFTER FORK REPO
  containers:
    - container: terraform
      image: azuredevopsiactemplatepipeline.azurecr.io/iac_azuredevops:v.1.0
      endpoint: azuredevopsiactemplatepipeline
      env:
        TF_STATE_BLOB_ACCOUNT_NAME: $(terraformStateBlobAccountName)
        TF_STATE_BLOB_CONTAINER_NAME: $(terraformStateBlobContainerName)
        TF_STATE_BLOB_FILE: terraform.tfstate
        ARM_SUBSCRIPTION_ID: $(terraformArmSubscriptionId)
        ARM_CLIENT_ID: $(terraformArmClientId)
        ARM_CLIENT_SECRET: $(terraformArmClientSecret)
        ARM_TENANT_ID: $(terraformArmTenantId)
        TF_IN_AUTOMATION: 1
        TF_LOG: trace
        TF_LOG_PATH: terraform.log

stages:
  - template: pipeline/terraform.yaml
    parameters:
      terraformPath: $(System.DefaultWorkingDirectory)/example-iac
      terraformVersion: 1.2.7
      resourceContainer: terraform
      envConfig:
        DEV:
          environmentDeploy: $(environmentDeployDEV)
          gitBranch: refs/heads/dev
        QA:
          environmentDeploy: $(environmentDeployQA)
          gitBranch: refs/heads/qa
        UAT:
          environmentDeploy: $(environmentDeployUAT)
          gitBranch: refs/heads/uat
        PRD:
          environmentDeploy: $(environmentDeployPRD)
          gitBranch: refs/heads/main
        PR:
          githubConnection: $(githubConnection)
          githubPullRequestId: $(System.PullRequest.PullRequestNumber)
          githubPRTargetBranch: $(System.PullRequest.TargetBranch)
