name: $(Date:yyyyMMdd)$(Rev:.r)

pool:
  name: Default
  vmImage: hosted-azure

variables:
  - group: azuredevops-iac-template-pipeline

resources:
  repositories:
    - repository: Iac-template
      type: github
      endpoint: github.com_alexbaptista # CHANGE HERE AFTER FORK REPO
      name: alexbaptista/azuredevops-iac-template-pipeline # CHANGE HERE AFTER FORK REPO
      ref: refs/tags/v.1.5 # CHANGE HERE AFTER FORK REPO
  containers:
    - container: terraform
      image: docker.io/alxbap/azuredevops-iac-template-pipeline:v.1.5
      env:
        TF_STATE_BLOB_ACCOUNT_NAME: $(terraformStateBlobAccountName)
        TF_STATE_BLOB_CONTAINER_NAME: $(terraformStateBlobContainerName)
        TF_STATE_BLOB_FILE: $(terraformStateBlobFile)
        ARM_SUBSCRIPTION_ID: $(terraformArmSubscriptionId)
        ARM_CLIENT_ID: $(terraformArmClientId)
        ARM_CLIENT_SECRET: $(terraformArmClientSecret)
        ARM_TENANT_ID: $(terraformArmTenantId)
        TF_IN_AUTOMATION: 1
        TF_LOG: trace
        TF_LOG_PATH: terraform.log

trigger:
  branches:
    include:
      - refs/heads/dev
      - refs/heads/qa
      - refs/heads/uat
      - refs/heads/main
  paths:
    exclude:
    - README.md

pr:
  branches:
    include:
      - refs/heads/dev
      - refs/heads/qa
      - refs/heads/uat
      - refs/heads/main
  paths:
    exclude:
    - README.md

stages:
  - template: pipeline/terraform.yaml@Iac-template
    parameters:
      terraformPath: $(System.DefaultWorkingDirectory)/example-iac
      terraformVersion: 1.2.7
      resourceContainer: terraform
      envConfig:
        DEV:
          environmentDeploy: dev
          gitBranch: refs/heads/dev
        QA:
          environmentDeploy: qa
          gitBranch: refs/heads/qa
        UAT:
          environmentDeploy: uat
          gitBranch: refs/heads/uat
        PRD:
          environmentDeploy: prd
          gitBranch: refs/heads/main
        PR:
          githubToken: $(githubToken)
