parameters:
  - name: terraformVersion
    type: string
    default: false
  - name: terraformPath
    type: string
    default: false
  - name: resourceContainer
    type: string
    default: false
  - name: envConfig
    type: object
    default: false
  - name: terraformConfig
    type: object
    default:
      DEV:
        terraformWorkspaceEnv: DEV
        terraformPlanFile: terraform.dev.tfplan
      QA:
        terraformWorkspaceEnv: QA
        terraformPlanFile: terraform.qa.tfplan
      UAT:
        terraformWorkspaceEnv: UAT
        terraformPlanFile: terraform.uat.tfplan
      PRD:
        terraformWorkspaceEnv: PRD
        terraformPlanFile: terraform.prd.tfplan

stages:
  - stage: DEV
    displayName: "Continuous Integration (DEV)"
    condition: ${{ eq(variables['Build.SourceBranch'], parameters.envConfig['DEV'].gitBranch) }}
    jobs:
      - template: "../pipeline-jobs/terraform-ci.yaml"
        parameters:
          terraformPlanFile: ${{ parameters.terraformConfig['DEV'].terraformPlanFile }}
          terraformWorkspaceEnv: ${{ parameters.terraformConfig['DEV'].terraformWorkspaceEnv }}
          terraformVersion: ${{ parameters.terraformVersion }}
          terraformPath: ${{ parameters.terraformPath }}
          environmentDeploy: ${{ parameters.envConfig['DEV'].environmentDeploy }}
          resourceContainer: ${{ parameters.resourceContainer }}
  - stage: QA
    displayName: "Continuous Delivery (QA)"
    condition: ${{ eq(variables['Build.SourceBranch'], parameters.envConfig['QA'].gitBranch) }}
    jobs:
      - template: "../pipeline-jobs/terraform-cd.yaml"
        parameters:
          terraformPlanFile: ${{ parameters.terraformConfig['QA'].terraformPlanFile }}
          terraformWorkspaceEnv: ${{ parameters.terraformConfig['QA'].terraformWorkspaceEnv }}
          terraformVersion: ${{ parameters.terraformVersion }}
          terraformPath: ${{ parameters.terraformPath }}
          environmentDeploy: ${{ parameters.envConfig['QA'].environmentDeploy }}
          resourceContainer: ${{ parameters.resourceContainer }}
  - stage: UAT
    displayName: "Continuous Delivery (UAT)"
    condition: ${{ eq(variables['Build.SourceBranch'], parameters.envConfig['UAT'].gitBranch) }}
    jobs:
      - template: "../pipeline-jobs/terraform-cd.yaml"
        parameters:
          terraformPlanFile: ${{ parameters.terraformConfig['UAT'].terraformPlanFile }}
          terraformWorkspaceEnv: ${{ parameters.terraformConfig['UAT'].terraformWorkspaceEnv }}
          terraformVersion: ${{ parameters.terraformVersion }}
          terraformPath: ${{ parameters.terraformPath }}
          environmentDeploy: ${{ parameters.envConfig['UAT'].environmentDeploy }}
          resourceContainer: ${{ parameters.resourceContainer }}
  - stage: PRD
    displayName: "Continuous Delivery (PRD)"
    condition: ${{ eq(variables['Build.SourceBranch'], parameters.envConfig['PRD'].gitBranch) }}
    jobs:
      - template: "../pipeline-jobs/terraform-cd.yaml"
        parameters:
          terraformPlanFile: ${{ parameters.terraformConfig['PRD'].terraformPlanFile }}
          terraformWorkspaceEnv: ${{ parameters.terraformConfig['PRD'].terraformWorkspaceEnv }}
          terraformVersion: ${{ parameters.terraformVersion }}
          terraformPath: ${{ parameters.terraformPath }}
          environmentDeploy: ${{ parameters.envConfig['PRD'].environmentDeploy }}
          resourceContainer: ${{ parameters.resourceContainer }}
  - stage: PR
    displayName: "Pull Request"
    condition: ${{ eq(variables['Build.Reason'], 'PullRequest') }}
    variables:
      - name: envTarget
        ${{ if eq(variables['System.PullRequest.TargetBranch'], parameters.envConfig['DEV'].gitBranch) }}:
          value: "DEV"
        ${{ if eq(variables['System.PullRequest.TargetBranch'], parameters.envConfig['QA'].gitBranch) }}:
          value: "QA"
        ${{ if eq(variables['System.PullRequest.TargetBranch'], parameters.envConfig['UAT'].gitBranch) }}:
          value: "UAT"
        ${{ if eq(variables['System.PullRequest.TargetBranch'], parameters.envConfig['PRD'].gitBranch) }}:
          value: "PRD"
    jobs:
      - template: "../pipeline-jobs/terraform-pr.yaml"
        parameters:
          terraformPlanFile: ${{ parameters.envConfig[variables.envTarget].terraformPlanFile }}
          terraformWorkspaceEnv: ${{ parameters.envConfig[variables.envTarget].terraformWorkspaceEnv }}
          terraformVersion: ${{ parameters.terraformVersion }}
          terraformPath: ${{ parameters.terraformPath }}
          resourceContainer: ${{ parameters.resourceContainer }}
          githubConnection: ${{ parameters.envConfig['PR']githubConnection}}