parameters:
  - name: envConfig
    type: object
    default: false
  - name: terraformConfig
    type: object
    default: false
  - name: terraformVersion
    type: string
    default: false
  - name: terraformPath
    type: string
    default: false
  - name: resourceContainer
    type: string
    default: false
  - name: githubConnection
    type: string
    default: false
  - name: githubPullRequestComment
    type: string
    default: "Write text comment"

jobs:
  - job: "TerraformPullRequest"
    displayName: "Terraform Pull Request"
    container: ${{ parameters.resourceContainer }}
    steps:
      - template: "../pipeline-tasks/pullrequest-env.yaml"
        parameters:
          envConfig: ${{ parameters.envConfig }}
          terraformConfig: ${{ parameters.terraformConfig }}
      - template: ../pipeline-tasks/tfenv-terraform-install.yaml
        parameters:
          terraformVersion: ${{ parameters.terraformVersion }}
      - template: ../pipeline-tasks/terraform-fmt.yaml
        parameters:
          terraformPath: ${{ parameters.terraformPath }}
      - template: ../pipeline-tasks/terraform-init.yaml
        parameters:
          terraformPath: ${{ parameters.terraformPath }}
      - template: ../pipeline-tasks/terraform-workspace.yaml
        parameters:
          terraformPath: ${{ parameters.terraformPath }}
          # terraformWorkspaceEnv: $(terraformWorkspaceEnvPR)
      - template: ../pipeline-tasks/terraform-validate.yaml
        parameters:
          terraformPath: ${{ parameters.terraformPath }}
      - template: ../pipeline-tasks/tflint-run.yaml
        parameters:
          terraformPath: ${{ parameters.terraformPath }}
      - template: ../pipeline-tasks/tfsec-run.yaml
        parameters:
          terraformPath: ${{ parameters.terraformPath }}
      - template: ../pipeline-tasks/terraform-plan.yaml
        parameters:
          terraformPath: ${{ parameters.terraformPath }}
          # terraformPlanFile: $(terraformPlanFilePR)
      - template: ../pipeline-tasks/github-pullrequest-comment.yaml
        parameters:
          githubConnection: ${{ parameters.githubConnection }}
          githubPullRequestComment: ${{ parameters.githubPullRequestComment }}
