parameters:
  - name: terraformWorkspaceEnv
    type: string
    default: false
  - name: terraformVersion
    type: string
    default: false
  - name: terraformPath
    type: string
    default: false
  - name: terraformPlanFile
    type: string
    default: false
  - name: resourceContainer
    type: string
    default: false
  - name: environmentDeploy
    type: string
    default: false
  - name: variableGroup
    type: string
    default: false

jobs:
  - deployment: "TerraformDeploy"
    displayName: "Terraform Deploy"
    variables:
      - group: ${{ parameters.variableGroup }}
    container: ${{ parameters.resourceContainer }}
      env:
        TF_STATE_BLOB_ACCOUNT_NAME: $(terraformStateBlobAccountName)
        TF_STATE_BLOB_CONTAINER_NAME: $(terraformStateBlobContainerName)
        TF_STATE_BLOB_FILE: $(terraformStateBlobFile)
        ARM_SUBSCRIPTION_ID: $(terraformArmSubscriptionId)
        ARM_CLIENT_ID: $(terraformArmClientId)
        ARM_CLIENT_SECRET: $(terraformArmClientSecret)
        ARM_TENANT_ID: $(terraformArmTenantId)
        TF_IN_AUTOMATION: 1
        TF_LOG: trace
        TF_LOG_PATH: terraform.log
    environment: ${{ parameters.environmentDeploy }}
    timeoutInMinutes: 10
    strategy:
      runOnce:
        deploy:
          steps:
            - template: ../pipeline-tasks/tfenv-terraform-install.yaml
              parameters:
                terraformVersion: ${{ parameters.terraformVersion }}
            - template: ../pipeline-tasks/terraform-init.yaml
              parameters:
                terraformPath: ${{ parameters.terraformPath }}
            - template: ../pipeline-tasks/terraform-workspace.yaml
              parameters:
                terraformPath: ${{ parameters.terraformPath }}
                terraformWorkspaceEnv: ${{ parameters.terraformWorkspaceEnv }}
            - template: ../pipeline-tasks/terraform-validate.yaml
              parameters:
                terraformPath: ${{ parameters.terraformPath }}
            - template: ../pipeline-tasks/terraform-plan.yaml
              parameters:
                terraformPath: ${{ parameters.terraformPath }}
                terraformPlanFile: ${{ parameters.terraformPlanFile }}
            - template: ../pipeline-tasks/terraform-apply.yaml
              parameters:
                terraformPath: ${{ parameters.terraformPath }}
                terraformPlanFile: ${{ parameters.terraformPlanFile }}