parameters:
  - name: envConfig
    type: object
    default: false
  - name: terraformConfig
    type: object
    default: false
  - name: terraformVersion
    type: string
    default: false
  - name: terraformPath
    type: string
    default: false
  - name: resourceContainer
    type: string
    default: false
  - name: variableGroup
    type: string
    default: false

jobs:
  - job: "TerraformPullRequest"
    displayName: "Terraform Pull Request"
    variables:
      - group: ${{ parameters.variableGroup }}
    container: ${{ parameters.resourceContainer }}
      env:
        TF_STATE_BLOB_ACCOUNT_NAME: $(terraformStateBlobAccountName)
        TF_STATE_BLOB_CONTAINER_NAME: $(terraformStateBlobContainerName)
        TF_STATE_BLOB_FILE: $(terraformStateBlobFile)
        ARM_SUBSCRIPTION_ID: $(terraformArmSubscriptionId)
        ARM_CLIENT_ID: $(terraformArmClientId)
        ARM_CLIENT_SECRET: $(terraformArmClientSecret)
        ARM_TENANT_ID: $(terraformArmTenantId)
        GITHUB_TOKEN: $(githubToken)
        TF_IN_AUTOMATION: 1
        TF_LOG: trace
        TF_LOG_PATH: terraform.log
    steps:
      - template: "../pipeline-tasks/pullrequest-env.yaml"
        parameters:
          envConfig: ${{ parameters.envConfig }}
          terraformConfig: ${{ parameters.terraformConfig }}
      - template: ../pipeline-tasks/tfenv-terraform-install.yaml
        parameters:
          terraformVersion: ${{ parameters.terraformVersion }}
      - template: ../pipeline-tasks/terraform-fmt.yaml
        parameters:
          terraformPath: ${{ parameters.terraformPath }}
      - template: ../pipeline-tasks/terraform-init.yaml
        parameters:
          terraformPath: ${{ parameters.terraformPath }}
      - template: ../pipeline-tasks/terraform-workspace.yaml
        parameters:
          terraformPath: ${{ parameters.terraformPath }}
      - template: ../pipeline-tasks/terraform-validate.yaml
        parameters:
          terraformPath: ${{ parameters.terraformPath }}
      - template: ../pipeline-tasks/tflint-run.yaml
        parameters:
          terraformPath: ${{ parameters.terraformPath }}
      - template: ../pipeline-tasks/tfsec-run.yaml
        parameters:
          terraformPath: ${{ parameters.terraformPath }}
      - template: ../pipeline-tasks/terraform-plan.yaml
        parameters:
          terraformPath: ${{ parameters.terraformPath }}
      - template: ../pipeline-tasks/terraform-plan-to-json.yaml
        parameters:
          terraformPath: ${{ parameters.terraformPath }}     
      - template: ../pipeline-tasks/github-pullrequest-comment.yaml
        parameters:
          terraformPath: ${{ parameters.terraformPath }}     
