name: Linux_Container_Workflow
on:
  push:
    branches:
      - main
    paths:
      - container-image/**

env:
  DOCKER_REPOSITORY: iac_azuredevops
  DOCKERFILE_PATH: ./container-image/Dockerfile

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Build and push image"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build -f ${{ env.DOCKERFILE_PATH }} -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.DOCKER_REPOSITORY }}:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.DOCKER_REPOSITORY }}:${{ github.sha }}
